name: test and build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Use Node.js 12.19.0'
        uses: actions/setup-node@v1
        with:
          node-version: '12.19.0'
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn run test
      - run: yarn run build
